site_name: Blizzard Starcraft II Tutorials

theme:
    name: readthedocs
    custom_dir: theme/

markdown_extensions:
    - markdown.extensions.toc:
        permalink: true

extra_css:
    - css/custom.css

dev_addr: '127.0.0.1:8001'